from django.contrib import admin
from lol.models import *
# Register your models here.


admin.site.register(Topic)
admin.site.register(Tournament)
admin.site.register(TournamentTheme)
admin.site.register(Team)
admin.site.register(Player)
admin.site.register(NewsComment)
admin.site.register(TournamentComment)
admin.site.register(WeiboComment)
admin.site.register(TopicComment)
admin.site.register(Weibo)
admin.site.register(News)
admin.site.register(SummonerSpells)
admin.site.register(Hero)
admin.site.register(Equipment)
admin.site.register(Position)
admin.site.register(TournamentTeamInfo)
admin.site.register(Match)
admin.site.register(Game)
admin.site.register(GamePlayer)
admin.site.register(PlayerInfo)
admin.site.register(TotalPlayerInfo)
admin.site.register(TotalTeamInfo)
admin.site.register(Tmp)
admin.site.register(SpiderConfig)
# admin.site.register(LOLInfoExtend)
