from django.conf.urls import patterns, include, url
from myadmin.api_views import *

urlpatterns = patterns('',
                       url(r'^login', AdminLoginView.as_view()),
                       url(r'^logout', AdminLogoutView.as_view()),
                       url(r'^index', AdminIndexView.as_view()),
                       url(r'^admin', AdminUserView.as_view()),
                       url(r'^tournament/(?P<tid>(\d)+)/match/(?P<mid>(\d)+)/game', AdminGameView.as_view()),
                       url(r'^tournament/(?P<tid>(\d)+)/match/(?P<mid>(\d)+)', AdminMatchModifyView.as_view()),
                       url(r'^tournament/(?P<tid>(\d)+)/match', AdminMatchView.as_view()),
                       url(r'^tournaments', AdminTournamentListView.as_view()),
                       url(r'^tournamenttheme', AdminTournamentThemeView.as_view()),
                       url(r'^tournament', AdminTournamentView.as_view()),
                       url(r'^game/(?P<gid>(\d)+)', AdminGameDeleteView.as_view()),
                       url(r'^gameplayer/(?P<gpid>(\d)+)', AdminGamePlayerDeleteView.as_view()),
                       url(r'^game', AdminGameDetailView.as_view()),
                       url(r'^user/(?P<uid>(\d)+)/forbid', AdminUserForbidView.as_view()),
                       url(r'^user/(?P<uid>(\d)+)', AdminUserDetailView.as_view()),
                       url(r'^users', AdminUserListView.as_view()),
                       url(r'^team/(?P<tid>(\d)+)', AdminTeamDetailView.as_view()),
                       url(r'^team', AdminTeamView.as_view()),
                       url(r'^player/(?P<pid>(\d)+)', AdminPlayerDetailView.as_view()),
                       url(r'^player', AdminPlayerView.as_view()),
                       )
